name: Testes de Raspagem E-commerce 

on:  # Disparadores do fluxo de trabalho (aqui usamos 'push')
  push: 
    branches: [ main ]  # Executa os testes em pushes na branch 'main'

jobs:
  run-tests:
    runs-on: ubuntu-latest  # Sistema operacional da máquina virtual

    steps:
      - uses: actions/checkout@v3   # Checkout do código do repositório

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # Versão do Python (ajuste)

      - name: Instalar Dependências
        run: pip install -r requirements.txt  # Assumindo um arquivo requirements.txt

      - name: Configurar WebDriver
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Ajuste  se necessário 

      - name: Iniciar Servidor HTTP
        run: python3 -m http.server & --directory public/

      - name: Executar os Testes
        run: python3 -m unittest

